"""scan history and privacy preferences

Revision ID: f44ed6350732
Revises: b04c64070cba
Create Date: 2026-09-12 15:22:04.923888
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import signalscope.db

revision: str = "f44ed6350732"
down_revision: str | None = "b04c64070cba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", signalscope.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("phash", sa.BigInteger(), nullable=True),
        sa.Column("band", sa.String(length=20), nullable=False),
        sa.Column("prob_ai", sa.Float(), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("image_key", sa.String(length=255), nullable=True),
        sa.Column("heatmap_key", sa.String(length=255), nullable=True),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_scans_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scans")),
    )
    op.create_index("ix_scans_sha256_model", "scans", ["sha256", "model_version"], unique=False)
    op.create_index("ix_scans_user_band", "scans", ["user_id", "band"], unique=False)
    op.create_index("ix_scans_user_created", "scans", ["user_id", "created_at"], unique=False)
    op.add_column(
        "users",
        sa.Column("save_images_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "users", sa.Column("retention_days", sa.Integer(), server_default=sa.text("90"), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "retention_days")
    op.drop_column("users", "save_images_default")
    op.drop_index("ix_scans_user_created", table_name="scans")
    op.drop_index("ix_scans_user_band", table_name="scans")
    op.drop_index("ix_scans_sha256_model", table_name="scans")
    op.drop_table("scans")
    # ### end Alembic commands ###
