"""users and auth sessions

Revision ID: b04c64070cba
Revises:
Create Date: 2026-09-12 00:00:32.031157
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import signalscope.db

revision: str = "b04c64070cba"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column(
            "role",
            sa.Enum("user", "reviewer", "admin", name="userrole", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", signalscope.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", signalscope.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_at", signalscope.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", signalscope.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("remember", sa.Boolean(), nullable=False),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("family_started_at", signalscope.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("created_at", signalscope.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("expires_at", signalscope.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", signalscope.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_auth_sessions_token_hash")),
    )
    op.create_index(op.f("ix_auth_sessions_family_id"), "auth_sessions", ["family_id"], unique=False)
    op.create_index("ix_auth_sessions_user_active", "auth_sessions", ["user_id", "revoked_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_auth_sessions_user_active", table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_family_id"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
